import type { Metadata } from "next";
import { Rethink_Sans, Cal_Sans } from "next/font/google";
import "./globals.css";

const rethink = Rethink_Sans({
  weight: ["400", "500", "600", "700","800"],
  subsets: ["latin"],
  variable: "--font-rethink",
  display: "swap",
});

const cal = Cal_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${rethink.variable} ${cal.variable} bg-white`}>
      <body className={rethink.className}>{children}</body>
    </html>
  );
}

